### ISSUE TITLE
Add an "+Add my City to the Census" button

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatasurvey#326]
#### Description

On the main page, next to the +Contribute Data to the Census, we should add a +Add My City to the Census button.

![screen shot 2014-04-24 at 2 50 46 pm](https://cloud.githubusercontent.com/assets/595778/2795433/8440fb84-cbfa-11e3-8a5e-950fda223f67.png)
#### Tasks
- [ ] Add the button to the front page
- [ ] Sign in
- [ ] Short form with place name
- [ ] Form should post to the Config spreadsheet Places tab
