### ISSUE TITLE
Email reviewers when a review is needed

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatasurvey#354]
#### Description

When a new dataset or revision is submitted, each reviewer should get a an email notifying them to go approve or reject that submission. 

I don't know the hosting service that the census uses. If it's Heroku, then [Mailgun](https://addons.heroku.com/mailgun) or [SendGrid](https://addons.heroku.com/sendgrid) can be set up easily.
#### Files

routes/census.js in `exports.submitPost`
#### Tasks
- [ ] Set up MailGun or SendGrid
- [ ] Within submitPost, use req.body.place to get the placename.
- [ ] Use the placename to get each local reviewers from #336 
- [ ] Some how return `allReviewers` from `canReview()` in #336 
- [ ] Use example code in the submitPost function to email `allReviewers`.
#### Example

```
for admin in admins:
        response = requests.post(
            # Production app14961102.mailgun.org
            # Staging app17090450.mailgun.org
            "https://api.mailgun.net/v2/app14961102.mailgun.org/messages",
            auth=("api", app.config['MAIL_GUN_KEY']),
            data={"from": "Andrew Hyder <andrewh@codeforamerica.org>",
                  "to": admin.email,
                  "subject": subject,
                  "html": html})
```

**Comment by Stephen-Gates** [comment]
As a reviewer I would really like to see this functionality implemented so I don't need to check the site each day to see if something needs to be reviewed. I think if someone makes the effort to add a submission then they should expect a quick turn-around of their work. Quick feedback encourages further contribution. 

Perhaps we should consider emailing the submitter (if they provided email address) at each stage: 
- your submission is has been received
- your submission has been reviewed (approved/rejected)

or allow them to subscribe to updates on a place, dataset or entry.

**Comment by morchickit** [comment]
I think this feature will drop in the global Index since we might not have country reviewer but thematic review. 
@Stephen-Gates - can a report be helpful here?

**Comment by schlos** [comment]
+1

**Comment by Stephen-Gates** [comment]
@morchickit there is no need for a report in my case (i.e. a Regional census) as the volumes are low and I can just view the ChangeLog on the site. What I was trying to avoid was having to go to the ChangeLog each day to see if there was a new submission. A simple e-mail saying, "there's a new submission" is all that's needed to tell editors to go look.

I understand that things are probably different for the Global Index given its size, the number of people involved,  and their differing focuses (country vs thematic). A report would probably be good in this case.

**Comment by pwalsh** [comment]
@morchickit I just realised this is a different request to the one we have scheduled in our user stories. What do you think if this?

**Comment by ondrae** [comment]
Ever since [place based reviewers](https://github.com/okfn/opendatacensus/pull/336) were added, this is even more needed. For the US census, we have one local volunteer reviewer for each city. An email when the rare update is made will help keep cities up to date.

**Comment by morchickit** [comment]
@pwalsh - we have to figure our a way do differ between issues that are for the local index, global index or both. In this case, it is not going to be relevant for the global index, but will for the local ones.

**Comment by pwalsh** [comment]
@ondrae ok.

@morchickit ok.
