### ISSUE TITLE
[super] Improved UX on Submission and Review forms - Sept 2014

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#433]
The UX of the Submission and Review forms has been identified as a critical area for improvement for the upcoming submission sprints. So, this is a very brief spec for improved UX for each of those workflows.

Much of the work to be done is shared as the forms are quite similar. 

So, first I'll address the commonalities, and then some specific points for each form.
## Common
- [x] Markdown for question descriptions #406 
- [x] Make additional info contextual - see [this diagram](https://docs.google.com/a/okfn.org/drawings/d/1KbzwJc0G2NKqLUJYortGMzsVkGb7nyGbOOL0BVO7FA4/edit)
  - [x] Is the data available online > show the URL input field in context when yes (1 hour)
  - [x] Is it in digital form? Format of data
    - Qu: what about non-digital (ans: format is about digital format not e.g. paper ...)
  - [x] Is it openly licensed? Url to license terms
  - [x] Publicly available? => Publisher info (or could drop publisher info??) - #420 
- [x] Remove/hide date data first openly available #419 
- [x] Remove/hide data quality questions #413 
- [x] When there _is_ a deviation from the current existing entry, indicate with a background color. This allows both submitters and reviews to glance at the form and instantly map the scope of deviations. (1 hour) 
- [x] _Format of data should be typeahead to encourage consolidation on standard formats_ (may already be implemented)
- [x] _Live preview of markdown in Comments and Details field #437_
- [x] <del>All UI elements related to "current entry" - don't show them, or at least do not show _No entry_ value, if there is no current entry. It is noise, and simply misleading on both he submission and review flows (1 hours)</del>
  - With new UX and visual indication of change, showing No entry looks reasonable
- [ ] <del>Add a simple toggle to hide the "Please read first" section. Or possibly, for submissions only - make it a modal popup, which then needs to be closed to get to the submission form. In any case - it currently takes too much real estate (1 hour)</del>
  - Wait until content is updated here - may ultimately not be necessary
- [ ] <del>The layout of the data availability questions could be greatly improved by changing the positioning of the "info" per question. The current layout uses lots of vertical space. Seeing as "info" is often a short paragraph per question, it would be a better use of space to show the info horizontally above/below each question. The *opposite is currently true of the text input fields - they have a lot of dead space to the right. (4 hours)</del>
  - Will leave this for the present as not sure of benefit/cost
- [ ] <del>Add ability to toggle on/off all info data in form. The toggle would have to always be visible to the user. (1-2 hours)</del>
  - Need to ask power-users if this would help
- [ ] <del>Integrate the tutorial text. I see two potentially useful options. (i) attempt to add in-context snippets from the tutorial text as applicable, or (ii) Add a fixed tab which is a call to action to open the tutorial. This could open in a new window, or, possibly as a side panel on the submission/review page. (TBA. from a few hours to a day)</del>
  - Suggest either not needed or will not require tech work (can be done by editing question info, top of page info etc)
- [ ] <del>Consider showing/hiding sections based on progress, in a "wizard-like" fashion. Make the form more digestable and require less scrolling (4-8 hours)</del>
  - leave now we have a refactor of layout
## Review Page (aka Submission Page)

Example: http://demo.census.okfn.org/submission/4dbc8a67-a4e9-4584-b54b-de4301b05985
- [x] Meta data on submission precedes the form - who submitted, date of submission and status (accepted, rejected etc)
- [x] Login call to action needs to be clearly accessible at the top of the main content area. A message like "if you are a reviewer, login to review". It is also possible to do something on the way to the submission page - like how users are redirected to login when they click to "add" a dataset (1/2 hour)
- [x] Accept/Reject action on the dataset should be either (a) at or near the top of the form. This makes it easier of the reviewer to take action at any time and also means they know what they need to do. (1/2 hour) 
- [x] Log message on review - dd a new field that encourages reviewers to comment on their decision (accept/reject). (1/2 hour) - #263 
- [ ] <del>Consider allowing the reviewer to permanently hide the "Please read first" section. It takes a lot of real estate, with little benefit to repeat reviewers. (could hide just for the session with cookies, or, as a state for the logged in user in the user database) (1 hour) </del>
  - Just make sure we do not show alert div if no instructions and leave it to census manager to choose to have instructions or not https://github.com/okfn/opendatacensus/blob/master/templates/submission/review.html#L20
- [ ] <del>Defer to an expert - need to talk with Mor a little more about it. But this is an alternative action to accept/reject (2-4 hours)</del> see #426 
- [ ] <del>The disqus integration. The current layout is sub-optimal. Rufus suggested either making the comments fixed and therefore move with the user through the document, or, even just removing. (TBA, need to discuss with Mor) 
  - Moving to #436. Probably defer for first round of changes and then see what things look like
