### ISSUE TITLE
Meta Issue: Sept 2014 2 week sprint

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatasurvey#434]
This issue is to help build a picture of the scope of the next 2 weeks of development --> Oct 6th. 

As it looks now, tasks are as follows (in this order):
1. [ ] UX enhancements on both Submission and Review forms #433 
   1. [ ] Support markdown for question descriptions #406 
   2. [ ] Small refactoring of data model (reviewer messages, ) #263 (0.5d?) #419 (30m)

Less important:
1. [ ] Various smaller UI/UX enhancements #421 #402 #399 #397 #374 #365
   - RP: i'd say #421 is v low priority and #402 was low priority. #399 is trivial (link to changes). #397 is low (atm) and #374 (timestamp of submission) is probably part of ux changes to submission page (e.g. related to showing status etc). #365 needs clarifying
### Non-Technical Changes
1. [ ] Integrate and deploy general content changes #407 #417 #416 and other content that is coming
   - Note these are all about content and require **no technical** changes (I wonder if we start moving this stuff out of github as not about general platform)
2. [ ] Remove anonymous login #432 (15m) - @morchickit 
   - Again specific to global site (already have the config option)
3. [ ] Related to above, add the feature for reviewers to engage an expert on a dataset #426
   - Seems likely this is not a change to the platform
