### ISSUE TITLE
NodeJS based static site generation for Index

### ISSUE THREAD

**Issue by brew** [okfn/opendatasurvey#853]
Static site generation:

1. Gather data from Survey (either using ORM or results of API)
2. Generate static pages from existing Nunjucks templates and gathered data
3. Push output static site to S3 bucket (see #854)

I propose using [Metalsmith](http://www.metalsmith.io/) as the static site generator. Metalsmith has a simple, pluggable pipeline workflow for manipulating content, and an extensive plugin ecosystem for the tasks we'll need to perform. Some suggested plugins we can make use of:

- https://github.com/kalamuna/metalsmith-env - expose env vars as metadata
- https://github.com/segmentio/metalsmith-metadata - global metadata from JSON files
- https://github.com/ahmadnassri/metalsmith-request - request data from the Survey API
- https://github.com/jaichandra/metalsmith-models - include JSON model data
- https://github.com/superwolff/metalsmith-layouts - template rendering (supports Nunjucks)
- https://github.com/mwishek/metalsmith-s3 - interactions with AWS

### Tasks

- [x] Gather data (Entries, Places, Datasets, Questions, and Sites) from Survey
- [x] Gather ancillary page data (Insights, Methodology, About, etc)
- [ ] Generate static pages:
  - [ ] Index
    - [x] Page
    - [ ] Stats (see #965)
  - [ ] Entry (see #843)
  - [ ] Places
    - [x] Table
    - [ ] Stats (see #965)
  - [x] Single Place (list of datasets)
    - [x] Table
    - [x] Stats
  - [x] Datasets
  - [x] Single Dataset (list of places)
    - [x] Table
    - [x] Stats
  - [x] Ancillary pages

**Comment by brew** [comment]
This can now be closed. Outstanding issues (Entry page, #843, and Stats, #965) created as separate issues.
