### ISSUE TITLE
Test the site on AWS after it's ready for testing

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatasurvey#923]
Do basic QA and review for the site. @brew to let us know when to start with that.

### Things That Need Looking At
- [x] Countries with no entries shouldn't be included in Index
- [x] Ancillary pages should be available from top navigation
    - [x] About
    - [x] Methodology
- [x] Connect Map to the status of openness (see #967)
- [x] Where should the Insights button link @morchickit ? [should be on the top navigation] #1015
- [x] Make download dump of database available [@brew, I can't see it] (see #969)
- [x] When inside a dataset organize the places based on their ranking (#970)
- [x] On home page sort by default according to rank (#970)
- [x] On home page 1586 Number of Entries Up from 970 in 2014 on the test site, should be up or down from 2015. Also, looks like it takes the 2015 number. (see #965)
- [x] Explanatory text for 'Percentage Open' on Places page needs review ([#1014] (https://github.com/okfn/opendatasurvey/issues/923#issuecomment-288146122))
- [x] Places for the same scores are not aligned, see the following screenshoot where countires with the same score got different ranks. 
![screen shot 2017-03-29 at 00 04 39](https://cloud.githubusercontent.com/assets/3273659/24431400/93b1a8de-1413-11e7-84a2-9b2bd7a4532e.png)

**Comment by brew** [comment]
@morchickit @tlacoyodefrijol 

The Index site is ready for testing, and available here: http://index.okfn.org.s3-website-eu-west-1.amazonaws.com/

Please edit this ticket description above to add to the list of Things That Need Looking At. There are many very obvious things that need fixing, but please add them anyway so we can keep track and spin off individual issues for them.

**Comment by morchickit** [comment]
Seems like the scores on the Survey site is different than the index site (See Afganistan 16% on the Index and 14% on the survey). Is this because of the Machine readable question?  (omitting HTML?)

**Comment by morchickit** [comment]
@brew to regenerate the site - so changes can be reflected when testing

**Comment by brew** [comment]
> @brew to regenerate the site - so changes can be reflected when testing

Index regenerated.

**Comment by morchickit** [comment]
OK- Couple of things - 
1. In places mode, places should be sorted by default as rank. Currently the default is A-Z
2. 1586 Number of Entries Up from 970 in 2014 on the test site, should be up or down from 2015. Also, looks like it takes the 2015 number.

**Comment by brew** [comment]
Can you edit the first comment and add these to the list. If this thread gets long, I may lose track of them :)

**Comment by morchickit** [comment]
Will do!

**Comment by brew** [comment]
There's explanatory text used for a pop-over on the place overview page that seems out-of-date (http://index-staging.okfn.org.s3-website-eu-west-1.amazonaws.com/place/ click the little ? next to 'Percentage Open'). It currently reads:

> This is the percentage of all the dataset entries that are open as per the Open Definition. We get one dataset entry for each dataset and place (e.g. Transport Timetables for the United Kingdom is one dataset entry). For each entry we check whether the dataset is fully open as per the Open Definition, and then divide by the total number of entries to get a percentage. &lt;a href=&quot;faq/#open-data&quot;&gt;Find out more about Open Data&lt;/a&gt;

I suggest @dannylammerhirt or @morchickit has a look.

**Comment by brew** [comment]
@morchickit It's not in the spreadsheet. Just let me know what you'd like it changed to.

**Comment by roll** [comment]
- go http://index.okfn.org.s3-website-eu-west-1.amazonaws.com/
- click `See insigths` button
- An error occurred
